package com.startcaft.ssm.mapper;

import com.startcaft.ssm.po.OrderDetailDto;

public interface OrderDetailDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    int insert(OrderDetailDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    int insertSelective(OrderDetailDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    OrderDetailDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    int updateByPrimaryKeySelective(OrderDetailDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    int updateByPrimaryKey(OrderDetailDto record);
}