package com.startcaft.ssm.mapper;

import com.startcaft.ssm.po.OrdersDto;

public interface OrdersDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    int insert(OrdersDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    int insertSelective(OrdersDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    OrdersDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    int updateByPrimaryKeySelective(OrdersDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    int updateByPrimaryKey(OrdersDto record);
}