package com.startcaft.ssm.mapper;

import com.startcaft.ssm.po.ItemsDto;

public interface ItemsDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    int insert(ItemsDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    int insertSelective(ItemsDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    ItemsDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    int updateByPrimaryKeySelective(ItemsDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(ItemsDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbggenerated Wed Oct 07 16:09:59 CST 2015
     */
    int updateByPrimaryKey(ItemsDto record);
}